// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnP0MNsiNXBj-EW--UH5ABp3HP5bJf6l4',
    appId: '1:721963740889:android:773b12eb42f731b88698c8',
    messagingSenderId: '721963740889',
    projectId: 'the-test-point',
    databaseURL: 'https://the-test-point-default-rtdb.firebaseio.com',
    storageBucket: 'the-test-point.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnP0MNsiNXBj-EW--UH5ABp3HP5bJf6l4',
    appId: '1:721963740889:ios:c19bac87f4cd365642e124',
    messagingSenderId: '721963740889',
    projectId: 'the-test-point',
    databaseURL: 'https://the-test-point-default-rtdb.firebaseio.com',
    storageBucket: 'the-test-point.firebasestorage.app',
    androidClientId:
        '721963740889-0ohq3pp1m8ihaaje0t0mt4knoadeiema.apps.googleusercontent.com',
    iosClientId:
        '721963740889-dh9pngcbov233e8hok2b4i142nem7vs4.apps.googleusercontent.com',
    iosBundleId: 'com.nextwave.thetestpoint',
  );
}
